ports:
  - port: 8080
    onOpen: open-browser
    visibility: public
  - port: 3000
    onOpen: ignore
    visibility: public
  - port: 4000
    onOpen: open-browser
    # making this public so that we can benefit from apollo studio
    visibility: public

tasks:
  - name: Startup
    before: npm i -g lerna
    init: lerna bootstrap
    command: lerna exec --parallel npm run start
  - name: Start NGINX
    command: nginx

vscode:
  extensions:
    - dsznajder.es7-react-js-snippets
    - esbenp.prettier-vscode
    - graphql.vscode-graphql
    - dbaeumer.vscode-eslint

image:
  file: .gitpod.Dockerfile
